### ISSUE TITLE
ClientError: Unable to parse csv on running training jobs

### ISSUE THREAD

**Issue by sandiemann** [aws/amazon-sagemaker-examples#1017] opened 2020-02-05 11:20 UTC
Hello AWS Team,

I have preprocessed data using Pyspark and serialize the model pipeline with Mleap and saved it to S3.  The sample CSV file contains a label, features. The features are been hashed with the Pyspark feature hasher function. 
`0,(262144,[4660,15287,35848,41726,87060,88435,88834,90006,98431,103359,118099,120849,139290,148114,159626,177894,188829,193907,195355,202340,204201,216676,238184,252654],[0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,0.0,1.0,5.0,3.0,1961.0,1.0,1.0,1.0,1.0,1.0,1.0])`
 
Now, I am trying to run the training job with 'Linear Learner' algorithm and the input data configuration with content-type: text/csv and predictor_type: binary_classifier.

The jobs are failing after a few minutes with `ClientError: Unable to parse csv: rows 1-1000, file /opt/ml/input/data/train/part-00000`.

Any heads up.

Regards,
Sanchit

**Comment by hsl89** [comment] 2021-01-22 19:56
Hi @sandiemann, closing this issue because we upgraded SageMaker Python SDK V2. Please feel free to open this issue again if the issue is not resolved in the updated version.

**Closed by hsl89** 2021-01-22 19:56 UTC
