### ISSUE TITLE
External dataset no longer available in XGBoost example notebook

### ISSUE THREAD

**Issue by szamarin** [aws/amazon-sagemaker-examples#1994] opened 2021-02-16 16:20 UTC
Looks like the dataset used in `introduction_to_applying_machine_learning/xgboost_customer_churn/xgboost_customer_churn.ipynb ` is no longer available

**Comment by seanpmorgan** [comment] 2021-02-16 16:40
Hi @szamarin thanks for reporting! Duplicate of https://github.com/aws/amazon-sagemaker-examples/issues/1966 and I should be pushing a synthetic dataset later today

**Closed by seanpmorgan** 2021-02-16 16:40 UTC
