### ISSUE TITLE
NameError: name 'data' is not defined

### ISSUE THREAD

**Issue by giusarno** [aws/amazon-sagemaker-examples#1051] opened 2020-02-16 22:43 UTC
Running the mnist pytorch example I get an error after having inserted the digit loading the input.html.
`
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-cdb55ebe7d7f> in <module>()
      1 import numpy as np
      2 
----> 3 image = np.array([data], dtype=np.float32)
      4 response = predictor.predict(image)
      5 prediction = response.argmax(axis=1)[0]

NameError: name 'data' is not defined
`
data should be set by the input.html and passed to the notebook. 

---------UPDATE 17022020

It turned out the problem is with JupiterLab but not normal Jupiter notebook. Is there a way to get it to work on JupiterLab ? Is it possible that the javascript silently fails as IPython is not defined or other issues ? I tried to add an alert after the execute command and teh alert does not comes up. It has to do with something related to IPython and JupiterLab.

**Comment by seanpmorgan** [comment] 2021-02-16 23:35
Thanks for reporting and sorry for the slow response.. duplicate of https://github.com/aws/amazon-sagemaker-examples/issues/979

**Closed by seanpmorgan** 2021-02-16 23:35 UTC
