### ISSUE TITLE
DeepAR Electricity Notebook: ModelError: when calling the InvokeEndpoint operation: Received client error (415) "Customer Error: Content-Type header value 'application/octet-stream' not supported

### ISSUE THREAD

**Issue by CloudaYolla** [aws/amazon-sagemaker-examples#1800] opened 2020-11-26 12:35 UTC
After the recent SageMaker SDK update, the predictions stopped working. Also, there are a couple of updates needed due to SDKv2 breaking changes. The solution will be submitted as a PR.

The DeepAR Electricity SageMaker Example notebook is not working: https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/deepar_electricity/DeepAR-Electricity.ipynb

How to reproduce
Run DeepAR Electricity sample NB. But change the line below as follows:

Issue
See NB line below creates errors:

`class DeepARPredictor(sagemaker.predictor.RealTimePredictor):`

When calling the predict function:

`predictor.predict(ts=timeseries[120], quantiles=[0.10, 0.5, 0.90]).head()`

Following error received:

```
---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
<ipython-input-33-74ca5ceda86e> in <module>
----> 1 predictor.predict(ts=timeseries[120], quantiles=[0.10, 0.5, 0.90]).head()

<ipython-input-31-1e80f2b8fe06> in predict(self, ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
     21         quantiles = [str(q) for q in quantiles]
     22         req = self.__encode_request(ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
---> 23         res = super(DeepARPredictor, self).predict(req)
     24         return self.__decode_response(res, ts.index.freq, prediction_time, return_samples)
     25 

/opt/conda/lib/python3.7/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant)
    117 
    118         request_args = self._create_request_args(data, initial_args, target_model, target_variant)
--> 119         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
    120         return self._handle_response(response)
    121 

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355         self.default_endpoint = default_endpoint or self.DEFAULT_ENDPOINT
    356 
--> 357     def resolve(self, service_name, region_name=None, endpoint_url=None,
    358                 is_secure=True):
    359         region_name = self._check_default_region(service_name, region_name)

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             'provide-client-params.{service_id}.{operation_name}'.format(
    675                 service_id=service_id,
--> 676                 operation_name=operation_name),
    677             params=api_params, model=operation_model, context=context)
    678         api_params = first_non_none_response(responses, default=api_params)

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (415) from model with message "Customer Error: Content-Type header value 'application/octet-stream' not supported (caused by KeyError)

Caused by: 'application/octet-stream'". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/deepar-electricity-demo-2020-11-26-07-22-10-480 in account ********* for more information.
```

**Comment by larkz** [comment] 2020-12-18 16:28
Please have a look at this issue again, on Sagemaker SDK v 2.20.0 when invoking,
```
predictor = sagemaker.RealTimePredictor(endpoint = endpoint_name, sagemaker_session=sagemaker_session, content_type = 'application/json')
req = "{some json data}"
predictor.predict(req)
```

The same error still exists,
```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (415) from model with message "Customer Error: Content-Type header value 'application/octet-stream' not supported (caused by KeyError)
```
I downgraded to Sagemaker SDK v 1.72.1 to resolve this issue, but it should be addressed in the newer versions.

**Comment by liangruibupt** [comment] 2020-12-31 05:43
Using SageMaker 2.19 encounter the same error

···
<ipython-input-43-e91a7460b7da> in <module>
----> 1 predictor.predict(ts=df.loc[end_training:, 'Global_active_power'], quantiles=[0.10, 0.5, 0.90], num_samples=100).head()

<ipython-input-41-b9d904935aea> in predict(self, ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
     20         quantiles = [str(q) for q in quantiles]
     21         req = self.__encode_request(ts, cat, dynamic_feat, num_samples, return_samples, quantiles)
---> 22         res = super(DeepARPredictor, self).predict(req)
     23         return self.__decode_response(res, ts.index.freq, prediction_time, return_samples)
     24 

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant)
    123 
    124         request_args = self._create_request_args(data, initial_args, target_model, target_variant)
--> 125         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
    126         return self._handle_response(response)
    127 

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (415) from model with message "Customer Error: Content-Type header value 'application/octet-stream' not supported (caused by KeyError)
···

**Comment by paul-cb** [comment] 2021-01-04 22:46
@liangruibupt @larkz  So in v2 you don't directly set `content_type` instead you set the content type in a Serializer instance. You can either do this in the Predictor's constructor or by setting `predictor.serializer` afterwards. Note that you can use an already created serializer class that allows you to specify a `content_type` or alternatively implement a class where you customize it to handle `content_type`.

**Comment by richwellman** [comment] 2021-01-05 16:53
To use the example notebooks in v2 I have had to add this bit of code before the prediction call.  I guess you could fix the original predictor object returned from the estimator as well by fixing that code.

# Create JSON Serializer instance and set content_type
json_serializer = sagemaker.serializers.JSONSerializer(content_type='application/json')

# Call the predictior constructor with the endpont_name set.  This creates a new predictor object.
predictor = sagemaker.predictor.Predictor(endpoint_name,serializer=json_serializer)

**Comment by larkz** [comment] 2021-01-06 10:39
Thank you @paul-cb, the issue was resolved by changing 
```
predictor = sagemaker.RealTimePredictor(endpoint = endpoint_name, sagemaker_session=sagemaker_session, content_type = 'application/json')

```
to
```
from sagemaker.predictor import json_serializer
predictor = sagemaker.predictor.RealTimePredictor(endpoint_name = endpoint_name, sagemaker_session=sagemaker_session, serializer=json_serializer)
```

**Comment by paul-cb** [comment] 2021-01-13 20:51
Thanks @larkz! 
This is solved, closing.

**Closed by paul-cb** 2021-01-13 20:51 UTC
