### ISSUE TITLE
Error: 'module' object has no attribute 'train_input_fn'

### ISSUE THREAD

**Issue by sahithyaswaminathan** [aws/amazon-sagemaker-examples#348] opened 2018-07-30 07:06 UTC
I have developed a custom code to implement a basic linear regression model (using sklearn library) and tried to use the Tensorflow container. However, I'm getting the following error:

2018-07-30 06:46:24,732 INFO - tf_container - ----------------------TF_CONFIG--------------------------
2018-07-30 06:46:24,733 INFO - tf_container - {"environment": "cloud", "cluster": {"master": ["algo-1:2222"]}, "task": {"index": 0, "type": "master"}}
2018-07-30 06:46:24,733 INFO - tf_container - ---------------------------------------------------------
2018-07-30 06:46:24,733 INFO - tf_container - creating RunConfig:
2018-07-30 06:46:24,733 INFO - tf_container - {'save_checkpoints_secs': 300}
2018-07-30 06:46:24,733 INFO - tensorflow - TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'master': [u'algo-1:2222']}, u'task': {u'index': 0, u'type': u'master'}}
2018-07-30 06:46:24,733 INFO - tf_container - creating an estimator from the user-provided model_fn
2018-07-30 06:46:24,733 INFO - tensorflow - Using config: {'_save_checkpoints_secs': 300, '_session_config': None, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': u'master', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff09d57df90>, '_model_dir': u's3://sagemaker-us-east-1-819159351269/sagemaker-tensorflow-2018-07-30-06-42-32-366/checkpoints', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_master': '', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': '', '_service': None, '_global_id_in_cluster': 0, '_save_summary_steps': 100, '_num_ps_replicas': 0}
2018-07-30 06:46:24,735 ERROR - container_support.training - uncaught exception during training: 'module' object has no attribute 'train_input_fn'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 70, in train
    train_spec = self._build_train_spec()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 116, in _build_train_spec
    invoke_args = self._resolve_input_fn_args(self.customer_script.train_input_fn)
AttributeError: 'module' object has no attribute 'train_input_fn'

 [3.948
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, run_tensorboard_locally)
    247                 tensorboard.join()
    248         else:
--> 249             fit_super()
    250 
    251     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    229         """
    230         def fit_super():
--> 231             super(TensorFlow, self).fit(inputs, wait, logs, job_name)
    232 
    233         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    178         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    179         if wait:
--> 180             self.latest_training_job.wait(logs=logs)
    181 
    182     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
    367     def wait(self, logs=True):
    368         if logs:
--> 369             self.sagemaker_session.logs_for_job(self.job_name, wait=True)
    370         else:
    371             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll)
    803 
    804         if wait:
--> 805             self._check_job_status(job_name, description, 'TrainingJobStatus')
    806             if dot:
    807                 print()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
    539         if status != 'Completed' and status != 'Stopped':
    540             reason = desc.get('FailureReason', '(No reason provided)')
--> 541             raise ValueError('Error training {}: {} Reason: {}'.format(job, status, reason))
    542 
    543     def wait_for_endpoint(self, endpoint, poll=5):

ValueError: Error training sagemaker-tensorflow-2018-07-30-06-42-32-366: Failed Reason: AlgorithmError: uncaught exception during training: 'module' object has no attribute 'train_input_fn'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 70, in train
    train_spec = self._build_train_spec()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 116, in _build_train_spec
    invoke_args = self._resolve_input_fn_args(self.customer_script.train_input_fn)
AttributeError: 'module' object has no attribute 'train_input_fn'

It'd be great, if I could know whether I've missed any part of the code or any workarounds available.

**Comment by djarpin** [comment] 2018-07-31 16:25
Hi @sahithyaswaminathan - Are you using TensorFlow as well in your task?  The SageMaker pre-built TensorFlow container is really designed to work with [TensorFlow Estimators](https://www.tensorflow.org/guide/estimators), so it's probably not the best choice if you just want to return a scikit linear regression model.  If that's your goal, the [scikit BYO example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb) is probably a better fit.  Thanks, and let me know if you have problems adapting that to your use case.

**Comment by sahithyaswaminathan** [comment] 2018-08-03 03:12
Hi @djarpin Thanks for your response. 
I tried to implement the code with the Tensorflow estimator and used Sagemakers pre-built tensorflow container. But, I am getting the following error while training the model:

"ValueError: Error training sagemaker-tensorflow-2018-08-03-03-03-09-518: Failed Reason: AlgorithmError: uncaught exception during training: index 18 is out of bounds for axis 0 with size 18"

2018-08-03 03:06:04,743 ERROR - container_support.training - uncaught exception during training: index 18 is out of bounds for axis 0 with size 18
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 73, in train
    tf.estimator.train_and_evaluate(estimator=estimator, train_spec=train_spec, eval_spec=eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 601, in run_master
    self._start_distributed_training(saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 853, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 691, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 798, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 117, in <lambda>
    train_input_fn = lambda: self.customer_script.train_input_fn(**invoke_args)
  File "/opt/ml/code/aus_nz_regressor.py", line 37, in train_input_fn
    return _generate_input_fn(training_dir, 'aus_nz_train.csv')
  File "/opt/ml/code/aus_nz_regressor.py", line 48, in _generate_input_fn
    features_dtype=np.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 59, in load_csv_with_header
    target[i] = np.asarray(row.pop(target_column), dtype=target_dtype)
IndexError: index 18 is out of bounds for axis 0 with size 18


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-cef441574c3b> in <module>()
----> 1 aus_nz_estimator.fit(train_data_location)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, run_tensorboard_locally)
    247                 tensorboard.join()
    248         else:
--> 249             fit_super()
    250 
    251     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    229         """
    230         def fit_super():
--> 231             super(TensorFlow, self).fit(inputs, wait, logs, job_name)
    232 
    233         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    178         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    179         if wait:
--> 180             self.latest_training_job.wait(logs=logs)
    181 
    182     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
    367     def wait(self, logs=True):
    368         if logs:
--> 369             self.sagemaker_session.logs_for_job(self.job_name, wait=True)
    370         else:
    371             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll)
    803 
    804         if wait:
--> 805             self._check_job_status(job_name, description, 'TrainingJobStatus')
    806             if dot:
    807                 print()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
    539         if status != 'Completed' and status != 'Stopped':
    540             reason = desc.get('FailureReason', '(No reason provided)')
--> 541             raise ValueError('Error training {}: {} Reason: {}'.format(job, status, reason))
    542 
    543     def wait_for_endpoint(self, endpoint, poll=5):

ValueError: Error training sagemaker-tensorflow-2018-08-03-03-03-09-518: Failed Reason: AlgorithmError: uncaught exception during training: index 18 is out of bounds for axis 0 with size 18
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 73, in train
    tf.estimator.train_and_evaluate(estimator=estimator, train_spec=train_spec, eval_spec=eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 601, in run_master
    self._start_distributed_training(saving_listeners=saving_li

I am finding it difficult to debug. So any thought would be great.

Thanks

**Comment by hsl89** [comment] 2021-01-27 22:35
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team

**Closed by hsl89** 2021-01-27 22:35 UTC
