### ISSUE TITLE
[Content Improvement] Fairness and Explainability with SageMaker Clarify

### ISSUE THREAD

**Issue by araitats** [aws/amazon-sagemaker-examples#2724] opened 2021-06-15 17:40 UTC
**Link to the notebook**
Fairness and Explainability with SageMaker Clarify
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_processing/fairness_and_explainability/fairness_and_explainability.ipynb

**What aspects of the notebook can be improved?**
Explaining Predictions
The shap calculation part hangs up. It looks like 30,000 sample as default is too large.  As the sample number is reduced to 500, the processing job was successfully completed. 
```
seed = 0
num_rows = 500
# Write a csv file used by SageMaker Clarify
test_explainavility_file = "test_explainavility.csv"
training_data.head(num_rows).to_csv(test_explainavility_file, index=False, header=False)
**test_explainavility_s3_path** = session.upload_data(
    test_explainavility_file, key_prefix="{}/data".format(prefix)
)

explainability_output_path = "s3://{}/{}/clarify-explainability".format(bucket, prefix)
explainability_data_config = clarify.DataConfig(
    s3_data_input_path=**test_explainavility_s3_path**,
    s3_output_path=explainability_output_path,
    label="Target",
    headers=training_data.columns.to_list(),
    dataset_type="text/csv",
)

```

This is happening internally. It seems like this shouldn't reach to 100%... 
```
/usr/local/lib/python3.7/site-packages/seaborn/categorical.py:1296: UserWarning: 80.4% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)
```
**What are your suggestions?**
Need more documentation around the shap calculation. If the input sample number of 30,000 is not recommended, it should be stated.

**Comment by xgchena** [comment] 2021-07-02 22:30
Thanks for reporting the problem. We believe it was caused by a bug in the Clarify container image, and the problem has been fixed in the latest release. I just had a try with the notebook in region us-west-2, and the explainability job passed in 15min. Would you retry the notebook to see if it works for you this time?

**Comment by larroy** [comment] 2022-04-18 17:40
Already fixed, @araitats please reopen if the issue still exists.

**Closed by larroy** 2022-04-18 17:40 UTC
