### ISSUE TITLE
bring_your_own Keras with callbacks

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#516] opened 2018-12-10 20:14 UTC
I'm trying to add callbacks like early stopping to the bring your own custom container Keras example, but the Estimator.fit() function fails when I compile the Keras model with callbacks. Is there any workaround for this?

**Comment by ChoiByungWook** [comment] 2018-12-11 23:10
Hello @austinmw,

Just for clarification, are you basing your container on this example? https://github.com/awslabs/amazon-sagemaker-examples/tree/d73e8cb736945fd589e30cee676cdf3b31d583ea/hyperparameter_tuning/keras_bring_your_own

If not, can you please point to the correct one?

Would it also be possible to get some more context, logs and maybe a small reproducible case? This would give us the details needed to figure out why your use case isn't working.

Thanks!

**Comment by ryanpeach** [comment] 2018-12-14 01:15
In which estimator types is keras supported? I see it seems to be supported in both Tensorflow and MXNet, but not much mention of it in either of the examples for those platforms.

**Comment by austinmw** [comment] 2018-12-14 05:05
@ChoiByungWook I managed to get callbacks working by switching to tf.keras and using tensorflow 1.12.0. I'm not able to use the ReduceLROnPlateau callback with tf.keras in Eager mode (because it requires the tf.train.optimizers), but I guess that's another issue altogether.

**Comment by hsl89** [comment] 2021-01-27 22:34
Dear SageMaker Community,
             In our attempts to provide this repository with a better level of support             going forward, we’re closing issues that were opened prior to the v2 release of the SDK.             This is because we believe that over time many of the issues             posted were solved with the latest release or other recent changes to the repo.             This will help us reallocate resources towards issues that are            more likely to still be relevant today.            Some of the issues experienced now can be resolved by referencing the            v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html             In this guide, you can find simple solutions to common notebook errors,             like the renaming of parameters and classes.            If you believe your issue is still ongoing and you have updated error            messaging or other info, please re-open it, and we investigate the issue.
            Best Regards,
            AWS SageMaker Team

**Closed by hsl89** 2021-01-27 22:34 UTC
Labels: type: bug, type: question
